### ISSUE TITLE
openmeeg_python_doc test failed

### ISSUE THREAD

**Issue by sagitter** [openmeeg/openmeeg#384]
Hi all.
openmeeg_python_doc is failed with the following error:

```
$ ctest3 -VV --force-new-ctest-process -j1 --output-on-failure --debug -R "openmeeg_python_doc"

...

/builddir/build/BUILD/cmake-3.14.5/Source/CTest/cmCTestRunTest.cxx:482     Start 1186: openmeeg_python_doc

/builddir/build/BUILD/cmake-3.14.5/Source/CTest/cmCTestRunTest.cxx:658 
1186: Test command: /usr/bin/python3 "/home/sagitter/rpmbuild/BUILD/openmeeg-2.4.2/build/wrapping/src/test_doc.py"

/builddir/build/BUILD/cmake-3.14.5/Source/cmCTest.cxx:150    Current_Time: Oct 10 11:46 CEST

/builddir/build/BUILD/cmake-3.14.5/Source/CTest/cmCTestRunTest.cxx:725 1186: Test timeout computed to be: 10000000

/builddir/build/BUILD/cmake-3.14.5/Source/CTest/cmCTestRunTest.cxx:44 1186: Traceback (most recent call last):

/builddir/build/BUILD/cmake-3.14.5/Source/CTest/cmCTestRunTest.cxx:44 1186:   File "/home/sagitter/rpmbuild/BUILD/openmeeg-2.4.2/build/wrapping/src/test_doc.py", line 5, in <module>

/builddir/build/BUILD/cmake-3.14.5/Source/CTest/cmCTestRunTest.cxx:44 1186:     assert inspect.getdoc(om.HeadMat) is not None

/builddir/build/BUILD/cmake-3.14.5/Source/CTest/cmCTestRunTest.cxx:44 1186: AssertionError

/builddir/build/BUILD/cmake-3.14.5/Source/CTest/cmCTestRunTest.cxx:811 1/1 Test #1186: openmeeg_python_doc ..............
/builddir/build/BUILD/cmake-3.14.5/Source/CTest/cmCTestRunTest.cxx:814 Testing openmeeg_python_doc ... 
/builddir/build/BUILD/cmake-3.14.5/Source/CTest/cmCTestRunTest.cxx:271 ***Failed    0.35 sec

/builddir/build/BUILD/cmake-3.14.5/Source/CTest/cmCTestRunTest.cxx:275 Traceback (most recent call last):
  File "/home/sagitter/rpmbuild/BUILD/openmeeg-2.4.2/build/wrapping/src/test_doc.py", line 5, in <module>
    assert inspect.getdoc(om.HeadMat) is not None
AssertionError


/builddir/build/BUILD/cmake-3.14.5/Source/cmCTest.cxx:150    Current_Time: Oct 10 11:46 CEST

/builddir/build/BUILD/cmake-3.14.5/Source/cmCTest.cxx:150    Current_Time: Oct 10 11:46 CEST

/builddir/build/BUILD/cmake-3.14.5/Source/cmCTest.cxx:150    Current_Time: Oct 10 11:46 CEST

/builddir/build/BUILD/cmake-3.14.5/Source/CTest/cmCTestTestHandler.cxx:546 
0% tests passed, 1 tests failed out of 1

/builddir/build/BUILD/cmake-3.14.5/Source/CTest/cmCTestTestHandler.cxx:563 
Total Test time (real) =   0.59 sec

/builddir/build/BUILD/cmake-3.14.5/Source/CTest/cmCTestTestHandler.cxx:594 
The following tests FAILED:

/builddir/build/BUILD/cmake-3.14.5/Source/CTest/cmCTestTestHandler.cxx:608 	1186 - openmeeg_python_doc (Failed)

/builddir/build/BUILD/cmake-3.14.5/Source/cmCTest.cxx:973 Errors while running CTest

/builddir/build/BUILD/cmake-3.14.5/Source/cmCTest.cxx:2388 Running a test(s) failed returning : 8
```
OpenMEEG-2.4.2
Fedora 32 (development branch)
Python-3.7+
Swig 3.0.12 or 4.0.1

**Comment by papadop** [comment]
I can confirm that I can reproduce the problem with fedora 30 machine.
It needs to use the option BUILD_REFERENCE_DOC.

**Comment by massich** [comment]
yes. build doc was turn off in #382 until we had a more stable version of the CIs. 
(I'm not working on it at the moment. Feel free to give it a try)

**Comment by papadop** [comment]
d9ocstrings.i is generated but not added to the module... Did that but I have some errors. I investigate...

**Comment by papadop** [comment]
Finally. The problem was probably that I did not rebuilt everything from scratch...
See PR #385
