### ISSUE TITLE
Compile error with Python-3.12

### ISSUE THREAD

**Issue by sagitter** [openmeeg/openmeeg#619]
Hi all.

I get this error when i try to [compile](https://kojipkgs.fedoraproject.org//work/tasks/3018/109243018/build.log) openmeeg-2.5.7 with `Python-3.12` and `setuptools-68.2.2`:

```
cd /builddir/build/BUILD/openmeeg-2.5.7/redhat-linux-build/wrapping/python && /usr/bin/python3.12 setup.py dist_info
running dist_info
creating openmeeg.egg-info
writing openmeeg.egg-info/PKG-INFO
writing dependency_links to openmeeg.egg-info/dependency_links.txt
writing requirements to openmeeg.egg-info/requires.txt
writing top-level names to openmeeg.egg-info/top_level.txt
writing manifest file 'openmeeg.egg-info/SOURCES.txt'
reading manifest file 'openmeeg.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'openmeeg.egg-info/SOURCES.txt'
creating '/builddir/build/BUILD/openmeeg-2.5.7/redhat-linux-build/wrapping/python/openmeeg-2.5.7.dist-info'
Traceback (most recent call last):
  File "/builddir/build/BUILD/openmeeg-2.5.7/redhat-linux-build/wrapping/python/setup.py", line 139, in <module>
    setup(
  File "/usr/lib/python3.12/site-packages/setuptools/__init__.py", line 103, in setup
    return distutils.core.setup(**attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/usr/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.12/site-packages/setuptools/dist.py", line 989, in run_command
    super().run_command(command)
  File "/usr/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.12/site-packages/setuptools/command/dist_info.py", line 112, in run
    bdist_wheel = self.get_finalized_command('bdist_wheel')
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 304, in get_finalized_command
    cmd_obj = self.distribution.get_command_obj(command, create)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 861, in get_command_obj
    cmd_obj = self.command_obj[command] = klass(self)
                                          ^^^^^^^^^^^
TypeError: 'NoneType' object is not callable
gmake[2]: *** [wrapping/python/CMakeFiles/openmeeg.dir/build.make:110: wrapping/python/openmeeg/_openmeeg.so] Error 1
```

**Comment by larsoner** [comment]
Can you run `from wheel.bdist_wheel import bdist_wheel as _bdist_wheel` on your system? Do you have `wheel` installed?

**Comment by sagitter** [comment]
> Do you have wheel installed?

`wheel` was missing; sorry for this fake issue.
