### ISSUE TITLE
om_minverser throwing std::bad_alloc

### ISSUE THREAD

**Issue by maedoc** [openmeeg/openmeeg#83]
I'm on a fresh CentOS 7 machine, with hdf5 & matio compiled from source, other packages from yum. My geom file looks like

```
# Domain Description 1.1

Interfaces 3

Interface Skull: "tvb_outer_skull_surface.tri"
Interface Cortex: "tvb_inner_skull_surface.tri"
Interface Head: "tvb_outer_skin_surface.tri"

Domains 4

Domain Scalp: Skull -Head
Domain Brain: -Cortex
Domain Air: Head
Domain Skull: Cortex -Skull
```

where the interfaces were obtained via `mne_watershed_bem` and have each 10242 vertices. `om_assemble` ran fine producing a 16GB head matrix.

Running `om_minverser head.mat head-inv.mat` with a Debug build, gdb's backtrace prints

```
#0  0x00007ffff58075f7 in raise () from /lib64/libc.so.6
#1  0x00007ffff5808ce8 in abort () from /lib64/libc.so.6
#2  0x00007ffff653e9d5 in __gnu_cxx::__verbose_terminate_handler() () from /lib64/libstdc++.so.6
#3  0x00007ffff653c946 in ?? () from /lib64/libstdc++.so.6
#4  0x00007ffff653c973 in std::terminate() () from /lib64/libstdc++.so.6
#5  0x00007ffff653cb93 in __cxa_throw () from /lib64/libstdc++.so.6
#6  0x00007ffff653d12d in operator new(unsigned long) () from /lib64/libstdc++.so.6
#7  0x00007ffff653d1c9 in operator new[](unsigned long) () from /lib64/libstdc++.so.6
#8  0x00007ffff7a6cd63 in OpenMEEG::LinOpValue::init (this=0xda39b410, n=2569477141, initval=0x7ffb2b3af010)
    at /home/mw/Work/openmeeg/libs/OpenMEEGMaths/include/linop.h:139
#9  0x00007ffff7a6cd02 in OpenMEEG::LinOpValue::LinOpValue (this=0xda39b410, n=2569477141, 
    initval=0x7ffb2b3af010) at /home/mw/Work/openmeeg/libs/OpenMEEGMaths/include/linop.h:135
#10 0x00007ffff680af84 in OpenMEEG::SymMatrix::reference_data (this=0x7fffffffdd20, array=0x7ffb2b3af010)
    at /home/mw/Work/openmeeg/libs/OpenMEEGMaths/include/symmatrix.h:79
#11 0x00007ffff680cfe5 in OpenMEEG::maths::MatlabIO::read<OpenMEEG::SymMatrix> (
    this=0x7ffff6a1f120 <OpenMEEG::maths::MatlabIO::prototype>, mat=0x608970, linop=...)
    at /home/mw/Work/openmeeg/libs/OpenMEEGMaths/include/MatlabIO.H:269
#12 0x00007ffff680ba34 in OpenMEEG::maths::MatlabIO::read (
    this=0x7ffff6a1f120 <OpenMEEG::maths::MatlabIO::prototype>, is=..., linop=...)
    at /home/mw/Work/openmeeg/libs/OpenMEEGMaths/include/MatlabIO.H:203
#13 0x00007ffff6808a78 in OpenMEEG::maths::operator>> (mio=..., linop=...)
    at /home/mw/Work/openmeeg/libs/OpenMEEGMaths/src/MathsIO.C:63
#14 0x00007ffff68056c8 in OpenMEEG::SymMatrix::load (this=0x7fffffffdd20, filename=0x7fffffffe1d4 "head.mat")
    at /home/mw/Work/openmeeg/libs/OpenMEEGMaths/src/symmatrix.cpp:218
#15 0x000000000040220e in main (argc=3, argv=0x7fffffffde58) at /home/mw/Work/openmeeg/src/minverser.cpp:72
```

The allocation in question is around 19 GB, where 23 GB of the system's 32 GB is already allocated to this process, so it's understandable that it fails, but it should probably say out of memory or something.

**Comment by maedoc** [comment]
In the mean time I will make smaller BEM surfaces...

**Comment by agramfort** [comment]
this is very likely to be fixed by latest release. closing.
